
spring.application.name=demo

spring.datasource.url=jdbc:postgresql://postgres:5432/crudPessoas
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springdoc=DEBUG
logging.level.org.springframework=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json
springdoc.api-docs.resolve-schema-properties=false

logging.level.org.springframework.web=DEBUG