# application-docker.properties

spring.datasource.url=jdbc:postgresql://postgres:5432/crudPessoas
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Swagger habilitado
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Porta do servidor (opcional)
server.port=8080
